backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Recettes" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - label: "Titre"
        name: "title"
        widget: "string"

      - label: "Auteur"
        name: "author"
        widget: "string"
        default: 'Sarah'

      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        default: ""

      - label: "Categorie"
        name: "categories"
        widget: "select"
        options:
          - "Entrée"
          - "Plat"
          - "Déssert"
        default: "Plat"

      - label: "Étiquettes"
        name: "tags"
        widget: "list"
        field:
          label: "Étiquette"
          name: "tag"
          widget: "string"

      - label: "Difficulté"
        name: "difficulty"
        widget: "number"
        default: 3
        min: 0
        max: 5

      - label: "Nombre de personnes"
        name: "nb_persons"
        widget: "number"
        default: 4
        min: 0

      - label: "Ingrédients"
        name: "ingredients"
        widget: "list"
        field:
          label: "Ingrédient"
          name: "ingredient"
          widget: "string"

      - label: "Image principale"
        name: "featured_img"
        widget: "image"

      - label: "Image pour les réseaux sociaux"
        name: "thumbnail"
        widget: "image"

      - label: "Recette"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Pages"
    files:
      - label: "À propos"
        name: "about"
        file: "source/a-propos/index.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Image principale"
            name: "featured_img"
            widget: "image"

          - label: "Image pour les réseaux sociaux"
            name: "thumbnail"
            widget: "image"

          - label: "Contenu"
            name: "body"
            widget: "markdown"

      - label: "Contact"
        name: "contact"
        file: "source/contact/index.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Image principale"
            name: "featured_img"
            widget: "image"

          - label: "Image pour les réseaux sociaux"
            name: "thumbnail"
            widget: "image"

          - label: "Contenu"
            name: "body"
            widget: "markdown"
