backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://sarah-cuisine.netlify.com
display_url: https://sarah-cuisine.netlify.com

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Recettes" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - label: "Titre"
        name: "title"
        widget: "string"

      - label: "Auteur"
        name: "author"
        widget: "string"
        default: 'Sarah'

      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        default: ""

      - label: "Categorie"
        name: "categories"
        widget: "select"
        options:
          - "Salé"
          - "Sucré"
        default: "Sucré"

      - label: "Tags"
        name: "tags"
        widget: "list"
        field:
          label: "Tag"
          name: "tag"
          widget: "string"

      - label: "Difficulté"
        name: "difficulty"
        widget: "number"
        default: 3
        min: 0
        max: 5

      - label: "Nombre de personnes"
        name: "nb_persons"
        widget: "number"
        default: 4
        min: 0

      - label: "Ingrédients"
        name: "ingredients"
        widget: "list"
        field:
          label: "Ingrédient"
          name: "ingredient"
          widget: "string"

      - label: "Mes commentaires"
        name: "myComments"
        widget: "markdown"

      - label: "Image principale"
        name: "featured_img"
        widget: "image"

      - label: "Image pour les réseaux sociaux"
        name: "thumbnail"
        widget: "image"

      - label: "Recette"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Pages"
    files:
      - label: "À propos"
        name: "about"
        file: "source/a-propos/index.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Image principale"
            name: "featured_img"
            widget: "image"

          - label: "Image pour les réseaux sociaux"
            name: "thumbnail"
            widget: "image"

          - label: type
            name: type
            widget: hidden
            default: contact

          - label: "Contenu"
            name: "body"
            widget: "markdown"

      - label: "Contact"
        name: "contact"
        file: "source/contact/index.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Image principale"
            name: "featured_img"
            widget: "image"

          - label: "Image pour les réseaux sociaux"
            name: "thumbnail"
            widget: "image"

          - label: "Contenu"
            name: "body"
            widget: "markdown"

      - label: "Contact success"
        name: "contact-success"
        file: "source/contact/success.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Image principale"
            name: "featured_img"
            widget: "image"

          - label: "Image pour les réseaux sociaux"
            name: "thumbnail"
            widget: "image"

          - label: "Contenu"
            name: "body"
            widget: "markdown"

  - name: "data"
    label: "Données"
    editor:
      preview: false
    files:
      - label: "Réglages"
        name: "settings"
        file: "source/_data/settings.yml"
        fields:
          - label: Menu
            name: menu
            widget: list
            allow_add: false
            fields:
              - name: name
                label: 'Nom de la page'
                widget: string

              - name: path
                label: 'Chemin vers la page'
                widget: string

              - name: active_condition
                label: "Condition d'activation"
                widget: 'select'
                required: false
                options:
                  - value: "home"
                    label: "Accueil"
                  - value: "post"
                    label: "Recette"

          - name: description
            label: Description
            widget: object
            fields:
              - name: title
                label: Titre
                widget: string

              - name: subtitle
                label: Sous titre
                widget: string

              - name: avatar
                label: Avatar
                widget: image

              - name: text
                label: Texte
                widget: text

          - name: footer
            label: Text de la partie basse
            widget: markdown

          - name: max_items_home
            label: "Nombre de recettes sur la page d'accueil"
            widget: number
