menu:
  - active_condition: home
    name: Accueil
    path: /
  - active_condition: post
    name: Mes Recettes
    path: /recettes
  - name: À Propos
    path: /a-propos
  - name: Contact
    path: /contact
description:
  avatar: /images/sarah.jpg
  subtitle: Moi c'est Sarah.
  text: >-
    J'aime cuisiner des recettes saines et gourmandes. Je les partage ici pour
    que vous puissiez vous régaler seul(e) ou en famille!
  title: Bienvenue!
footer: © Sarah Cuisine 2019
max_items_home: 4
