node_sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false

header_bg: https://images.unsplash.com/photo-1529566652340-2c41a1eb6d93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80
